-- sales definition

CREATE TABLE sales (
	order_id INTEGER,
	order_date VARCHAR(50),
	status VARCHAR(50),
	item_id REAL,
	sku VARCHAR(50),
	qty_ordered REAL,
	price REAL,
	value REAL,
	discount_amount REAL,
	total REAL,
	category VARCHAR(50),
	payment_method VARCHAR(50),
	bi_st VARCHAR(50),
	cust_id REAL,
	"year" INTEGER,
	"month" VARCHAR(50),
	ref_num INTEGER,
	"Name Prefix" VARCHAR(50),
	"First Name" VARCHAR(50),
	"Middle Initial" VARCHAR(50),
	"Last Name" VARCHAR(50),
	Gender VARCHAR(50),
	age REAL,
	full_name VARCHAR(50),
	"E Mail" VARCHAR(50),
	"Customer Since" VARCHAR(50),
	SSN VARCHAR(50),
	"Phone No. " VARCHAR(50),
	"Place Name" VARCHAR(50),
	County VARCHAR(50),
	City VARCHAR(50),
	State VARCHAR(50),
	Zip INTEGER,
	Region VARCHAR(50),
	"User Name" VARCHAR(50),
	Discount_Percent REAL
);